import Head from "next/head";
import styles from "@styles/default.module.scss";
import Link from "next/link";

const Index = () => {
  return (
    <>
      <Head>
        <title>About Tomoya Tokunaga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main> */}
      <div className={styles.description}>
        <h1>Hello,</h1>
        <p>
          I&apos;m Tomoya Tokunaga, a software engineer based in Tokyo, Japan.
          <br />
          <br />
          Currently working at Rakuten Mobile as a lead developer of web
          application for B2C customers. I&apos;m working both frontend and
          backend part of the application using: NodeJS (ReactJS, ExpressJS),
          Python, SQL, Kubernetes, etc
          <br />
          <br />
          All my personal projects, past experiences and skills/technologies are
          listed below.
        </p>
        <div>
          <Link href="/algorithms">Algorithms</Link>
        </div>
      </div>
      {/* </main> */}
    </>
  );
};

export default Index;
