import Head from "next/head";
import { useEffect, useState } from "react";

import styles from "@styles/default.module.css";
import Grid from "@components/algorithms/Grid/Grid";
import { useWindowSize } from "@utils/index";

const pageWidthPadding = 30;
const pageHeightPadding = 50;

const AlgorithmHome = () => {
  const [width, height] = useWindowSize();
  const [rowSize, setRowSize] = useState(0);
  const [colSize, setColSize] = useState(0);

  useEffect(() => {
    console.log("row", rowSize);
    setRowSize(Math.floor((height - pageHeightPadding * 4) / 30));
    setColSize(Math.floor((width - pageWidthPadding * 4) / 30));
  }, [width, height]);

  return (
    <>
      <Head>
        <title>About Tomoya Tokunaga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.description}>
        <h1>Hello</h1>
        <div style={{ display: "flex", justifyContent: "center" }}>
          <Grid originalRowSize={rowSize} originalColSize={colSize} />
        </div>
      </div>
    </>
  );
};

export default AlgorithmHome;
