import Head from "next/head";
import { useCallback, useEffect, useState } from "react";

import styles from "@styles/default.module.css";
import Grid from "@components/algorithms/Grid/Grid";
import { bfs } from "./pathfinding";
import { useWindowSize } from "@utils/hooks";

const gridWrapperId = "grid-wrapper";

const AlgorithmHome = () => {
  const { width, height } = useWindowSize();
  const [rowSize, setRowSize] = useState(0);
  const [colSize, setColSize] = useState(0);
  const [algorithmExecuted, setAlgorithmExecuted] = useState(false);

  const onStartClick = useCallback(() => {
    if (!algorithmExecuted) {
      setAlgorithmExecuted(!algorithmExecuted);
    }
  }, [algorithmExecuted]);

  useEffect(() => {
    if (width && height) {
      const gridWrapper = document.getElementById(gridWrapperId);
      const gridHeight = gridWrapper?.clientHeight || height;
      const gridWidth = gridWrapper?.clientWidth || width;
      setColSize(Math.floor(gridWidth / 30));
      setRowSize(Math.floor((gridHeight - 100) / 30));
    }
  }, [width, height]);

  return (
    <>
      <Head>
        <title>Algorithm | Pathfinding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.description}>
        <h2>Pathfinding</h2>
        <button onClick={onStartClick}>Start</button>
        <div
          id={gridWrapperId}
          style={{ display: "flex", justifyContent: "center" }}
        >
          <Grid
            rowSize={rowSize}
            colSize={colSize}
            pathfindingAlgorithm={bfs}
            algorithmExecuted={algorithmExecuted}
            setAlgorithmExecuted={setAlgorithmExecuted}
          />
        </div>
      </div>
    </>
  );
};

export default AlgorithmHome;
